name: Build and Deploy Tauri App

on:
  push :
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Tauri CLI
      run: npm install -g @tauri-apps/cli

    - name: Install dependencies
      run: npm install

    - name: Build Tauri app
      uses: tauri-apps/tauri-action@v0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        TAURI_PRIVATE_KEY: ${{ secrets.TAURI_PRIVATE_KEY }}
        TAURI_KEY_PASSWORD: ${{ secrets.TAURI_KEY_PASSWORD }}
      with:
        # tauri-action replaces \_\_VERSION\_\_ with the app version
        tagName: ${{ github.ref_name }}
        releaseName: "Keysaver v__VERSION__"
        releaseBody: |
          ${{steps.build_changelog.outputs.changelog}}
          See the assets to download this version and install.
        releaseDraft: true
        prerelease: false

    - name: Automate GitHub Releases
  # You may pin to the exact commit or the version.
  # uses: nekofar/create-github-release@9ec0f8de0cdc2a6f1350c70e6c3435c3a1e28707
      uses: nekofar/create-github-release@v1.0.12
      with:
    # The tag name for the release (e.g., v1.0.0)
        tag: "V_VERSION_"
          
