name: Build and Deploy Tauri App

on:
  push :
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Tauri CLI
      run: npm install -g @tauri-apps/cli

    - name: Install dependencies
      run: npm install

    - name: Build Tauri app
      run: npm run tauri build

    - name: Deploy to GitHub Releases
      uses: softprops/gotta-release@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        draft: true
        prerelease: false
        title: "Keysaver Update"
        body: "New release on Keysaver"
        artifact: "path/to/your/app/artifact"
      env:
        TAURI_UPDATER_PUBLIC_KEY: ${{ secrets.TAURI_UPDATER_PUBLIC_KEY }}
        TAURI_UPDATER_PRIVATE_KEY: ${{ secrets.TAURI_UPDATER_PRIVATE_KEY }}
